config/routes.rb
Rails.application.routes.draw do

  get 'shipping', to: 'shipping#test'
  post 'shipping/score'

  get 'status', to: 'status#status'

  devise_for :customers, path: '/', path_names: { sign_in: 'login', sign_out: 'logout' }

  root 'company#home'
  get '/about', to: 'company#about'

  resources :categories, only: :show
  resources :brands, only: :show
  resources :products, only: :show
  resources :deals, only: :index
  get '/cart', to: 'products#cart', as: :cart
  get '/products/:id/order', to: 'products#add_to_cart', as: :order_product
  post '/products/order', to: 'products#add_multiple_to_cart', as: :order_products
  get '/products/:id/remove', to: 'products#remove_from_cart', as: :remove_product

  post 'messages', to: 'messages#create'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :admin do
    post 'scoring/score'
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    context = JSON.parse(message_params[:context].presence || '{}') # set the context variable as a Hash
    context.merge! current_customer.conversation_context if context.empty?  # add customer context if first message
    context[:locale] = message_params[:locale]

    response = Conversation.send message_params[:content], context  # send message and context to Watson Conversation

    # Extract messages and context 
    @messages = response[:output][:text]
    @context = response[:context].to_json

    respond_to { |format| format.js } # respond with Javascript to update chat bubble
  end

  private

  def message_params
    params.permit(:content, :context, :locale)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_chat_window.html.erb
<div id="chat-zone">
  
  <div id="chat-window">
    <div id="chat-flow">
      <div id="chat-messages">
      </div>
    </div>

    <div id="chat-input-container">
      <%= render 'messages/input' %>
    </div>
  </div>

  <div id="chat-button">
    <%= image_tag 'watson-logo-round.png', id: 'watson-button' %>
    <div id="close-button">
      <span id="close-icon">X</span>
      <div class="gradient"></div>
    </div>
  </div>
  
</div>

<%= render 'messages/user_message' %>

<%= javascript_include_tag 'chat_window' %>

<%= hidden_field_tag 'chat_window_delay', ENV['CHAT_WINDOW_DELAY'] || 1 %>
<%= javascript_include_tag 'auto_chat' %>

app/views/messages/_input.html.erb
<%= form_tag messages_path, id: 'new_message', remote: true do %>
    <%= text_field_tag :content, '', id: 'chat-input', placeholder: 'Send a message...' %>
    <%= hidden_field_tag :context, '', id: 'message_context' %>
<% end %>

app/views/messages/_user_message.html.erb
<script id="user-message-template" type="text/x-handlebars-template">
  <div class="message-wrapper user">
    <%= image_tag 'head.svg', class: 'message-icon user-icon' %>
    <div class="message user-message">
      {{ message }}
    </div>
  </div>
</script>

app/views/messages/_watson_message.html.erb
<% type = 'watson' %>
<div class="message-wrapper <%= type %>">
  <%= image_tag 'head.svg', class: 'message-icon user-icon' if type == 'user' %>
  <div class="message <%= type %>-message">
    <%= content.html_safe %>
  </div>
  <%= image_tag 'watson-logo-round.png', class: 'message-icon watson-icon' if type == 'watson' %>
</div>

app/views/messages/create.js.erb
<% @messages.each do |message| %>
    $("#chat-messages").append("<%= j render partial: 'watson_message', locals: {content: message} %>");
<% end %>
$("#message_context").val("<%== j @context  %>");
$("#chat-messages img").load(function(){ ChatWindow.received_message(); });