config/routes.rb
Rails.application.routes.draw do

  get 'shipping', to: 'shipping#test'
  post 'shipping/score'

  get 'status', to: 'status#status'

  devise_for :customers, path: '/', path_names: { sign_in: 'login', sign_out: 'logout' }

  root 'company#home'
  get '/about', to: 'company#about'

  resources :categories, only: :show
  resources :brands, only: :show
  resources :products, only: :show
  resources :deals, only: :index
  get '/cart', to: 'products#cart', as: :cart
  get '/products/:id/order', to: 'products#add_to_cart', as: :order_product
  post '/products/order', to: 'products#add_multiple_to_cart', as: :order_products
  get '/products/:id/remove', to: 'products#remove_from_cart', as: :remove_product

  post 'messages', to: 'messages#create'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :admin do
    post 'scoring/score'
  end

end

app/controllers/shipping_controller.rb
class ShippingController < ApplicationController
  
  def test
    @schema_params = SHIPPING_PARAMS
    @shipment = session[:shipment]
  end
  
  def score
    
    # convert integer type params to integers
    @input = {}
    scoring_params.each do |param, val|
      @input[param] = case SHIPPING_PARAMS[param][:type]
                                when 'integer'
                                  val.to_i
                                when 'decimal'
                                  val.to_f
                                else
                                  val
                              end
    end
    
    if @@deployment
      # get the score
      score = @@deployment.score @input
      session[:shipment] = @input.dup
      
      # generate view variables
      @input = ShippingController.reorder(@input, SHIPPING_PARAMS_ORDER)
      @input.transform_keys! do |key|
        rec = MlScoringParam.find_by_name(key)
        rec&.alias ? rec.alias : key
      end
      @delay        = score['values'][0].last
      @normal_time  = 1 + @input['Distance (km)'] / 1000
      @arrival_date = Date.today + @normal_time + @delay.round(2)
      
      @color = case
                 when @delay < 1 then
                   'green'
                 when @delay < 2 then
                   'gold'
                 else
                   'red'
               end
      
    else
      redirect_to :shipping, flash: { error: 'ERROR: There is no available model for predicting shipping delay' }
    end
    
  end
  
  private
  
  def scoring_params
    params.permit(SCHEMA_PARAMS_ORDER)
  end
  
  @@deployment = Deployment.where("name like ?", "%delay%").first
  
  SHIPPING_PARAMS_ORDER = %w(totalCases totalWeight shipFrom shipFromState shipTo shipToState distance destWeatherConds)
  
  def self.reorder(hash, order)
    new_hash = {}
    order.each do |key|
      new_hash[key] = hash[key]
    end
    new_hash
  end
  
  # get a mapping of input schema param name to type
  
  schema_params = @@deployment&.get_input_schema&.map { |param|
    rec = MlScoringParam.find_by_name(param['name'])
    [param['name'], {
      type: param['metadata']['columnInfo']['columnTypeName'],
      name: rec&.alias ? rec.alias : key,
      record: rec
    }]
  }.to_h
  
  SCHEMA_PARAMS_ORDER = schema_params.keys
  
  SHIPPING_PARAMS = ShippingController.reorder(schema_params, SHIPPING_PARAMS_ORDER)
  
end

app/helpers/shipping_helper.rb
module ShippingHelper
  
  SMALL = 7
  LARGE = 14
  SPACE = 1
  
  def shipping_input (param, hash, value)
    
    location = param.include? 'ship'
    weather = param.include? 'Weather'
    paren_content = param == 'totalCases' ? 'items' : hash[:name][/\((\w+)\)/,1]
    size = paren_content == 'State' ? SMALL : LARGE
    input_group = paren_content == 'Country' || weather ? {} : {class: "input-group"}
    
    content_tag :div, style: "flex: #{size};" do
  
      content_tag :div, input_group do
    
        if param.include? 'State'
          concat content_tag :span, paren_content, class: "input-group-addon"
        end
    
        if hash[:record].ml_scoring_param_options.empty?
          concat text_field_tag param, value, type: type(hash[:type].split('(')[0]), class: 'form-control'
    
        else
          concat select_tag param,
                            options_from_collection_for_select(hash[:record].ml_scoring_param_options,
                                                               :value, :value, value),
                            class: 'form-control'
        end
    
        unless location or weather
          concat content_tag :span, paren_content, class: "input-group-addon"
        end
  
      end
      
    end
    
  end
  
  def spacing (param)
  
    unless param.include? 'State'
      size = param.include?('Weather') ? SMALL+SPACE : LARGE
      size = SPACE if param.include? 'ship'
      content_tag(:div, nil, style: "flex: #{size};")
    end
    
  end
  
  def addon param, units, input
    if param.include? 'Ship'
      state = input["#{param}(State)"]
      ", #{state}" unless state == 'NA' 
    else
      units
    end
  end
  
end

app/views/shipping/_banner.html.erb
<div id="shipping_images_container">
  <%= image_tag 'container.jpg' %>
  <%= image_tag 'dock.jpg' %>
  <%= image_tag 'train.jpg' %>
  <%= image_tag 'truck.jpg' %>
</div>

<br>

app/views/shipping/score.html.erb
<div id="shipping-input-container">
  <div id="shipping-output">
  
    <%= render 'banner' %>
    
    <div class="flex header_margins">
      <h1 class="bold">Supply Chain Prediction</h1>
    </div>
  
    <br>
    
    <table id="shipping-output-table" class="table">
      <thead>
      <tr class="header_row">
        <th>Shipment Details</th>
        <th>Arrival</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>
          <table id="shipping-input-table" class="table">
            <% @input.each do |k,v| %>
              <% unless k.include? 'State' %>
              <tr>
                <% comps = k.split(/[()]/) %>
                <th class="input-col"><%= comps[0] %></th>
                <td><%= v %> <%= addon comps[0], comps[1], @input %></td>
              </tr>
              <% end %>
            <% end %>
          </table>
        </td>
        <td id="output_table_container">
          <table id="output_table">
            <tr>
              <th>Predicted Delay:</th>
            </tr>
            <tr>
              <th><span style="color: <%= @color  %>;"><%= @delay.round(2) %> days</span></th>
            </tr>
          </table>
        </td>
      </tr>
      </tbody>
    </table>
    
  </div>
  
  <br>
  <p class="center-container">
    <%= link_to shipping_path, class: 'btn btn-lg' do %>
      <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;&nbsp;New Prediction
    <% end %>
  </p>
  
</div>

app/views/shipping/test.html.erb
<div id="shipping-input-container">
  <div id="shipping-input">
    
    <%= render 'banner' %>
    
    <div class="flex header_margins">
      <h1 class="bold">Supply Chain Predictor</h1>
    </div>
  
    <br><br>
    
    <%= form_tag shipping_score_path do %>
    <table id="shipping-input-table" class="table">
      <% @schema_params.each do |param, hash| %>
        <% if param.include? 'State' %>
          <%= shipping_input param, hash, @shipment&.fetch(param) %>
        <% else %>
              </div>
            </td>
          </tr>
          <tr>
            <th class="col-md-2">
              <%= label_tag param, hash[:name].split('(')[0] %>
            </th>
            <td class="col-md-5">
              <div style="display: flex">
                <%= shipping_input param, hash, @shipment&.fetch(param) %>
                <%= spacing param %>
        <% end %>
      <% end %>
    </table>
    
    <div class="center-container" style="margin-top: 80px">
      <%= submit_tag 'Predict Delay', class: 'btn btn-lg' %>
    </div>
    <% end %>
    
  </div>
</div>