config/routes.rb
Rails.application.routes.draw do

  get 'shipping', to: 'shipping#test'
  post 'shipping/score'

  get 'status', to: 'status#status'

  devise_for :customers, path: '/', path_names: { sign_in: 'login', sign_out: 'logout' }

  root 'company#home'
  get '/about', to: 'company#about'

  resources :categories, only: :show
  resources :brands, only: :show
  resources :products, only: :show
  resources :deals, only: :index
  get '/cart', to: 'products#cart', as: :cart
  get '/products/:id/order', to: 'products#add_to_cart', as: :order_product
  post '/products/order', to: 'products#add_multiple_to_cart', as: :order_products
  get '/products/:id/remove', to: 'products#remove_from_cart', as: :remove_product

  post 'messages', to: 'messages#create'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :admin do
    post 'scoring/score'
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find params[:id]
    redirect_to root_path, flash: { error: 'Could not find the category ' + params[:name] } unless @category
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_products.html.erb
<div class="row">
  <% products.each do |product| %>
    <%= render product %>
  <% end %>
</div>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<%= render partial: 'products/thumbnails', locals: {products: @category.products} %>

<%= render 'messages/chat_window' if customer_signed_in? and @category.name == 'Smartphones' %>