config/routes.rb
Rails.application.routes.draw do

  get 'shipping', to: 'shipping#test'
  post 'shipping/score'

  get 'status', to: 'status#status'

  devise_for :customers, path: '/', path_names: { sign_in: 'login', sign_out: 'logout' }

  root 'company#home'
  get '/about', to: 'company#about'

  resources :categories, only: :show
  resources :brands, only: :show
  resources :products, only: :show
  resources :deals, only: :index
  get '/cart', to: 'products#cart', as: :cart
  get '/products/:id/order', to: 'products#add_to_cart', as: :order_product
  post '/products/order', to: 'products#add_multiple_to_cart', as: :order_products
  get '/products/:id/remove', to: 'products#remove_from_cart', as: :remove_product

  post 'messages', to: 'messages#create'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :admin do
    post 'scoring/score'
  end

end

app/models/product.rb
# noinspection ALL
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :brand
  has_many :features
  has_many :deals
  has_many :trigger_deals, :class_name => 'Deal', :foreign_key => 'trigger_product_id'
  has_one :deployment
  
  serialize :color_options, Array
  serialize :storage_options, Array
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  
  attr_accessor :discount_price
  
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  
  # Check for Machine Learning Model-based special offers 
  def check_special_offer(customer, cart)
    
    # Check for potential deals
    potential_deals = trigger_deals.where(special: true)
    unless potential_deals.empty?
      potential_deal = potential_deals.first
      
      # Find the deployment for the the model of this deal's product
      if !(cart.include? potential_deal.product) && potential_deal.product.deployment
        
        # Get the score from the given deployment
        probability = potential_deal.product.deployment.get_score customer
        
        # Offer the deal if the probability is greater than 80%
        return potential_deal if probability > 0.8
      end
      
    end
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :init_cart_if_empty


  def show
    @product = Product.find params[:id]

    # Check for any special offers
    if customer_signed_in?
      cart = Product.find(session[:cart])
      cart.each do |product|
        @special_deal ||= product.check_special_offer(current_customer, cart)
      end
    end
    
    @deals   = @product.trigger_deals.where(special: false) + @product.deals.where(special: false)
    @in_cart = session[:cart].include? @product.id
  end


  def add_multiple_to_cart
    if order_products_params[:additional_product]
      additional_product = Product.find order_products_params[:additional_product]
      put_in_cart additional_product if additional_product
    end
    add_to_cart
  end


  def add_to_cart
    @product = Product.find order_products_params[:id]
    put_in_cart @product if @product
    check_new_deals
    redirect_to action: 'cart'
  end


  def remove_from_cart
    product = Product.find params[:id]
    session[:cart].delete product.id
    change_cart_price(-1*product.price)
    check_removed_deals
    redirect_to action: 'cart'
  end


  def cart
    @cart = Product.find session[:cart]
    apply_discounts

    # Check for any special offers
    if customer_signed_in?
      @cart.each do |product|
        @special_deal ||= product.check_special_offer(current_customer, @cart)
      end
    end
  end


  private


  def check_new_deals
    Product.find(session[:cart]).each do |product|
      deals = product.deals
      deals.each do |deal|
        if deal&.price and !session[:deals].include?(deal.id)
          if deal.trigger_product.nil? or session[:cart].include?(deal.trigger_product.id)
            session[:deals] << deal.id
            change_cart_price -1*discount(deal)
          end
        end
      end
    end
  end


  def apply_discounts
    session[:deals].each do |deal_id|
      deal                      = Deal.find deal_id
      idx                       = @cart.index deal.product
      @cart[idx].discount_price = deal.price if idx
    end
  end


  def check_removed_deals
    Deal.find(session[:deals]).each do |deal|
      if !session[:cart].include? deal.product.id || deal.trigger_product and (session[:cart] & [deal.trigger_product.id, deal.product.id]).length < 2
        session[:deals].delete deal.id
        change_cart_price discount(deal)
      end
    end
  end


  def discount(deal)
    deal.product.price - (deal.price || 0)
  end


  def init_cart_if_empty
    unless session[:cart]
      session[:cart]       = []
      session[:deals]      = []
      session[:cart_price] = 0
    end
  end


  def order_products_params
    params.permit(:id, :additional_product)
  end


  def put_in_cart(product)
    unless session[:cart].include? product.id
      session[:cart] << product.id
      change_cart_price(product.discount_price || product.price)
    end
  end


  def change_cart_price(price)
    session[:cart_price] = BigDecimal.new(session[:cart_price]) + price
  end


end

app/helpers/products_helper.rb
module ProductsHelper
  
  def display_price(price, discount_price=nil)
    content_tag :div, class: 'price' do
      if discount_price
        concat(content_tag :p, content_tag(:strike, decimal_to_euros(price), style: 'font-size: 18px') )
      end
      concat( content_tag :p, bold_price(discount_price || price) )
    end
  end
  
  def bold_price(price)
    content_tag :strong, style: 'font-size: 24px' do
      decimal_to_euros price
    end
  end

  def decimal_to_euros(price)
    content_tag :span, style: 'white-space: nowrap;' do
      number_to_currency price, 
                       unit: t('currency'), 
                       separator: t('separator'), 
                       delimiter: t('delimiter'), 
                       format: '%u %n'
    end
  end
  
  def stock_status(in_stock)
    css_class = in_stock ? 'in-stock' : 'coming-soon'
    content_tag :p, class: css_class do
      in_stock ? 'In Stock' : 'Coming Soon!'
    end
  end
  
end

app/views/products/_cart_button.html.erb
<% big = (defined?(big) and big) %>
<% two = defined? additional_product %>
<%= form_tag order_products_path, method: 'post' do |f| %>
  <%= hidden_field_tag :id, product.id %>
  <%= hidden_field_tag :additional_product, additional_product.id if two %>
  <%= submit_tag "Add#{' Both' if two} To Cart", class: "btn btn-lg #{'big-' if big}btn-cart" %>
<% end %>

app/views/products/_details_button.html.erb
<p><%= link_to 'Details', product, class: 'btn btn-lg btn-details', role: 'button' %></p>

app/views/products/_details_cart_button.html.erb
<p>
  <%= render partial: 'products/details_button', locals: {product: product} %>
  <%= render partial: 'products/cart_button', locals: { product: product} %>
</p>

app/views/products/_details_cart_buttons.html.erb
<p>
  <%= render partial: 'products/details_button', locals: {product: product} %>
  <%= render partial: 'products/cart_button', locals: { product: product} %>
</p>

app/views/products/_product.html.erb
<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="thumbnail">
    <div class="product-image">
      <div>
      <%= link_to product_path(product), id: "#{product.friendly_id}-img-link" do %>
        <%= image_tag product.image.url %>
      <% end %>
      </div>
    </div>
    <div class="caption">
      <div class="product-name"><%= link_to product.name, product_path(product) %></div>
      <p class="brand-name"><%= 'by '+product.brand.name if product.brand %></p>
      <p class="price"><%= decimal_to_euros product.price %></p>
    </div>
    <div class="thumbnail-cart-button">
      <%= render partial: 'products/cart_button', locals: { product: product} %>
    </div>
  </div>
</div>

app/views/products/_thumbnails.html.erb
<div class="row">
  <% products.each do |product| %>
    <%= render product %>
  <% end %>
</div>

app/views/products/cart.html.erb
<% if @special_deal and not @cart.include? @special_deal.product %>
  <%= render partial: 'deals/deal', locals: {deal: @special_deal} %>
<% end %>
<h1 id="shopping-cart-title">Shopping Cart</h1>
<table id='shopping-cart'>
  <tr>
    <th></th>
    <th></th>
    <th>Price</th>
    <th>Quantity</th>
    <th></th>
  </tr>
<% @cart.each do |product| %>
  <tr id="<%= product.friendly_id %>">
    <td class="col-md-3"><%= image_tag product.image.url %></td>
    <td>
      <%= link_to content_tag(:h4, product.name, class: 'product-name'), product %>
      <p>by <%= product.brand.name %></p>
      <%= stock_status !product.preorder %>
    </td>
    <td>
      <%= display_price(product.price, product.discount_price) %>
    </td>
    <td style="text-align: right">
      <p>
      <select class="quantity-select">
        <% (1...10).each do |i| %>
          <option><%= i %></option>
        <% end %>
      </select>
      </p>
      <p>
        <%= link_to 'Remove', remove_product_path(product) %>
      </p>
    </td>
    <td class="col-md-1"></td>
  </tr>
<% end %>
</table>
<br>
<div style="text-align: right;">
<h3 id="subtotal">
  Subtotal (<%= (session[:cart] || []).length %> items): <%= decimal_to_euros(session[:cart_price] || 0) %>
</h3>
<br>
<p>
  <%= link_to 'Proceed To Checkout', '#', class: 'btn btn-lg', id: 'checkout' %>
</p>
</div>

app/views/products/show.html.erb
<%= render @special_deal if @special_deal %>

<div class="product-panel">
  <div class="product-image">
    <%= image_tag(@product.image.url) %>
  </div>
  <div class="product-info">
    <div>
      <h2 class="product-name"><%= @product.name %></h2>
      <h3 class="brand-name"><%= @product.brand.name %> inc.</h3>
      <% if @special_deal %>
          <%= display_price @product.price, @special_deal.price %>
      <% else %>
        <h3 class="price"><%= decimal_to_euros @product.price %></h3>
      <% end %>
      <ul class="features-list">
        <% @product.features.each do |feature| %>
        <li><span><%= feature.description %></span></li>
        <% end %>
      </ul>
      <br>
      <% unless @product.color_options.empty? %>
          <p class="choose-your">CHOOSE YOUR COLOR</p>
          <div class="btn-group" data-toggle="buttons">
            <% @product.color_options.each do |color| %>
            <label class="btn btn-default btn-lg option option-<%= color.downcase %>">
              <input type="radio" name="options" id="<%= color %>" autocomplete="off"><%= color %>
            </label>
            <% end %>
          </div>
      <% end %>
      <br><br>
      <% unless @product.storage_options.empty? %>
          <p class="choose-your">CHOOSE YOUR STORAGE</p>
          <div class="btn-group" data-toggle="buttons">
            <% @product.storage_options.each do |size| %>
                <label class="btn btn-default btn-lg option option-storage">
                  <input type="radio" name="options" id="size-<%= size %>" autocomplete="off"><%= size %> GB
                </label>
            <% end %>
          </div>
      <% end %>
      
      <p style="margin-top: 40px;">
        <% if @in_cart %>
            <%= link_to 'View in your Cart >', cart_path, class: 'btn btn-lg big-btn-cart' %>
        <% else %>
            <%= link_to 'Add To Cart', order_product_path(@product), class: 'btn btn-lg big-btn-cart' %>
        <% end %>
      </p>
    </div>
  </div>
</div>

<%= render @deals unless @special_deal %>